name: Test

on:
  push:
    branches:
      - main
jobs:
  deploy-kepler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Test'
        run: | 
         echo ENV AWS_ACCOUNT_ENV_VARIABLE ${{ env.AWS_ACCOUNT_ENV_VARIABLE }}
         echo ENV AWS_ACCOUNT_REPO_VARIABLE ${{ env.AWS_ACCOUNT_REPO_VARIABLE }}
         echo VARS AWS_ACCOUNT_ENV_VARIABLE ${{ vars.AWS_ACCOUNT_ENV_VARIABLE }}
         echo VARS AWS_ACCOUNT_ENV_VARIABLE ${{ vars.AWS_ACCOUNT_ENV_VARIABLE }}